#![allow(dead_code)]
/// Standard library function signatures
/// Format: "fn(param1, param2) -> return_type"
pub const BUILTINS: &[(&str, &str)] = &[
    // === I/O ===
    ("print", "fn(text) -> nothing"),
    ("println", "fn(text) -> nothing"),
    ("input", "fn(prompt) -> text"),
    ("exit", "fn(code) -> nothing"),
    // === String Operations ===
    ("trim", "fn(text) -> text"),
    ("len", "fn(text) -> num"),
    ("upper", "fn(text) -> text"),
    ("lower", "fn(text) -> text"),
    ("split", "fn(text, text) -> list[text]"),
    ("join", "fn(list[text], text) -> text"),
    ("replace", "fn(text, text, text) -> text"),
    ("contains", "fn(text, text) -> bool"),
    ("starts_with", "fn(text, text) -> bool"),
    ("ends_with", "fn(text, text) -> bool"),
    ("slice", "fn(text, num, num) -> text"),
    // === Number Operations ===
    ("floor", "fn(dec) -> num"),
    ("ceil", "fn(dec) -> num"),
    ("round", "fn(dec) -> num"),
    ("abs", "fn(num) -> num"),
    ("sqrt", "fn(dec) -> dec"),
    ("pow", "fn(num, num) -> num"),
    ("log", "fn(dec, dec) -> dec"),
    ("sin", "fn(dec) -> dec"),
    ("cos", "fn(dec) -> dec"),
    ("tan", "fn(dec) -> dec"),
    ("min", "fn(num, num) -> num"),
    ("max", "fn(num, num) -> num"),
    ("clamp", "fn(num, num, num) -> num"),
    // === List Operations ===
    ("first", "fn(list[T]) -> maybe[T]"),
    ("last", "fn(list[T]) -> maybe[T]"),
    ("rest", "fn(list[T]) -> list[T]"),
    ("sort", "fn(list[T]) -> list[T]"),
    ("reverse", "fn(list[T]) -> list[T]"),
    ("take", "fn(list[T], num) -> list[T]"),
    ("drop", "fn(list[T], num) -> list[T]"),
    ("each", "fn(list[T], fn(T) -> U) -> list[U]"),
    ("keep", "fn(list[T], fn(T) -> bool) -> list[T]"),
    ("find", "fn(list[T], fn(T) -> bool) -> maybe[T]"),
    ("any", "fn(list[T], fn(T) -> bool) -> bool"),
    ("all", "fn(list[T], fn(T) -> bool) -> bool"),
    ("fold", "fn(list[T], U, fn(U, T) -> U) -> U"),
    ("append", "fn(list[T], T) -> list[T]"),
    ("prepend", "fn(list[T], T) -> list[T]"),
    ("concat", "fn(list[T], list[T]) -> list[T]"),
    ("unique", "fn(list[T]) -> list[T]"),
    // === Map Operations ===
    ("keys", "fn(map[K, V]) -> list[K]"),
    ("values", "fn(map[K, V]) -> list[V]"),
    ("has", "fn(map[K, V], K) -> bool"),
    ("get", "fn(map[K, V], K) -> maybe[V]"),
    ("set", "fn(map[K, V], K, V) -> map[K, V]"),
    ("remove", "fn(map[K, V], K) -> map[K, V]"),
    ("merge", "fn(map[K, V], map[K, V]) -> map[K, V]"),
    // === Time/Date ===
    ("now", "fn() -> num"),
    ("today", "fn() -> text"),
    ("sleep", "fn(num) -> nothing"),
    ("format_time", "fn(num, text) -> text"),
    ("parse_time", "fn(text, text) -> num"),
    // === JSON ===
    ("to_json", "fn(any) -> text"),
    ("from_json", "fn(text) -> any"),
    // === HTTP ===
    ("fetch", "fn(text) -> ok[any, text]"),
    ("fetch_post", "fn(text, any) -> ok[any, text]"),
    ("encode_url", "fn(text) -> text"),
    ("decode_url", "fn(text) -> text"),
    // === Crypto/Hashing ===
    ("hash", "fn(text) -> text"),
    ("hash_file", "fn(text) -> text"),
    ("random", "fn() -> dec"),
    ("random_int", "fn(num, num) -> num"),
    ("uuid", "fn() -> text"),
    // === Environment ===
    ("env", "fn(text) -> maybe[text]"),
    ("env_or", "fn(text, text) -> text"),
    ("env_set", "fn(text, text) -> nothing"),
    // === Filesystem ===
    ("read_file", "fn(text) -> ok[text, text]"),
    ("write_file", "fn(text, text) -> ok[nothing, text]"),
    ("file_exists", "fn(text) -> bool"),
    ("list_dir", "fn(text) -> list[text]"),
    // === Type Checking ===
    ("is_num", "fn(any) -> bool"),
    ("is_text", "fn(any) -> bool"),
    ("is_list", "fn(any) -> bool"),
    ("is_map", "fn(any) -> bool"),
    ("is_nothing", "fn(any) -> bool"),
    ("type_of", "fn(any) -> text"),
];

/// Check if a name is a builtin function
pub fn is_builtin(name: &str) -> bool {
    BUILTINS.iter().any(|(n, _)| *n == name)
}

/// Get signature for a builtin
pub fn get_builtin_sig(name: &str) -> Option<&'static str> {
    BUILTINS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, sig)| *sig)
}

/// List of reserved keywords that cannot be used as identifiers
pub const RESERVED_KEYWORDS: &[&str] = &[
    "shape",
    "think",
    "let",
    "mut",
    "give",
    "fail",
    "wait",
    "when",
    "otherwise",
    "and",
    "or",
    "not",
    "is",
    "in",
    "with",
    "nothing",
    "async",
    "on",
    "ok",
    "maybe",
    "each",
    "keep",
    "fold",
    "take",
    "sort",
    "screen",
    "piece",
    "box",
    "words",
    "tap",
    "field",
    "image",
    "remember",
    "load",
    "routes",
    "connect",
    "go",
    "back",
    "needs",
    "param",
    "show",
    "hide",
    "enter",
    "leave",
    "hover",
    "press",
    "loop",
    "move",
    "ease",
    "duration",
    "serve",
    "database",
    "task",
    "queue",
    "live",
    "guard",
    "auth",
    "reply",
    "transaction",
    "every",
    "workers",
    "retry",
    "port",
    "prefix",
    "path",
    "secret",
    "expires",
    "kind",
    "url",
    "pool",
    "as",
    "broadcast",
    "yes",
    "no",
    "num",
    "dec",
    "text",
    "bool",
    "list",
    "map",
    "any",
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DEL",
];

/// Check if a name is reserved
pub fn is_reserved(name: &str) -> bool {
    RESERVED_KEYWORDS.contains(&name)
}
