// VED App — generated by vedc. Do not edit.
// Target: wasm32-unknown-unknown (pure WASM, no JS framework)
#![allow(dead_code, unused_variables, non_upper_case_globals, static_mut_refs, unused_mut, unused_must_use, unused_imports)]
#![no_std]

extern crate alloc;
use alloc::{string::String, vec::Vec, format};

// ─── allocator (required for no_std + alloc) ─────────────────────────────────
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! { loop {} }

// ─── Canvas / browser API imports (provided by the VED HTML bootstrap) ────────
extern "C" {
    fn ved_clear(r: u8, g: u8, b: u8);
    fn ved_set_fill(ptr: *const u8, len: u32);
    fn ved_set_stroke(ptr: *const u8, len: u32);
    fn ved_set_alpha(a: f64);
    fn ved_fill_rect(x: f64, y: f64, w: f64, h: f64);
    fn ved_fill_rrect(x: f64, y: f64, w: f64, h: f64, r: f64);
    fn ved_stroke_rrect(x: f64, y: f64, w: f64, h: f64, r: f64, bw: f64);
    fn ved_set_shadow(blur: f64, ox: f64, oy: f64, c_ptr: *const u8, c_len: u32);
    fn ved_clear_shadow();
    fn ved_set_font(ptr: *const u8, len: u32);
    fn ved_fill_text(ptr: *const u8, len: u32, x: f64, y: f64);
    fn ved_measure_text(ptr: *const u8, len: u32) -> f64;
    fn ved_draw_image(src_ptr: *const u8, src_len: u32, x: f64, y: f64, w: f64, h: f64);
    fn ved_push_transform(cx: f64, cy: f64, sx: f64, sy: f64);
    fn ved_pop_transform();
    fn ved_request_frame();
}

// ─── String bridge: pass &str to JS without allocator overhead ───────────────
static mut STR_BUF: [u8; 8192] = [0u8; 8192];
unsafe fn with_str<R, F: Fn(*const u8, u32) -> R>(s: &str, f: F) -> R {
    let b = s.as_bytes();
    let n = if b.len() < STR_BUF.len() { b.len() } else { STR_BUF.len() - 1 };
    let dst = &mut STR_BUF[..n];
    dst.copy_from_slice(&b[..n]);
    f(STR_BUF.as_ptr(), n as u32)
}

// ─── Canvas helpers ───────────────────────────────────────────────────────────
#[inline] fn v_fill(c: &str)      { unsafe { with_str(c, |p,l| ved_set_fill(p,l)) } }
#[inline] fn v_stroke(c: &str)    { unsafe { with_str(c, |p,l| ved_set_stroke(p,l)) } }
#[inline] fn v_font(f: &str)      { unsafe { with_str(f, |p,l| ved_set_font(p,l)) } }
#[inline] fn v_rect(x:f64,y:f64,w:f64,h:f64)        { unsafe { ved_fill_rect(x,y,w,h) } }
#[inline] fn v_rrect(x:f64,y:f64,w:f64,h:f64,r:f64) { unsafe { ved_fill_rrect(x,y,w,h,r) } }
#[inline] fn v_brect(x:f64,y:f64,w:f64,h:f64,r:f64,bw:f64) { unsafe { ved_stroke_rrect(x,y,w,h,r,bw) } }
#[inline] fn v_text(s:&str,x:f64,y:f64) { unsafe { with_str(s,|p,l| ved_fill_text(p,l,x,y)) } }
#[inline] fn v_measure(s:&str) -> f64   { unsafe { with_str(s,|p,l| ved_measure_text(p,l)) } }
#[inline] fn v_image(src:&str,x:f64,y:f64,w:f64,h:f64) {
    unsafe { with_str(src, |p,l| ved_draw_image(p,l,x,y,w,h)) }
}
#[inline] fn v_shadow(blur:f64,ox:f64,oy:f64,c:&str) {
    unsafe { with_str(c, |p,l| ved_set_shadow(blur,ox,oy,p,l)) }
}
#[inline] fn v_clear_shadow() { unsafe { ved_clear_shadow() } }
#[inline] fn v_alpha(a:f64)   { unsafe { ved_set_alpha(a) } }

// ─── Layout rect ─────────────────────────────────────────────────────────────
#[derive(Clone, Copy, Debug)]
struct Rect { x: f64, y: f64, w: f64, h: f64 }
impl Rect {
    #[inline]
    fn hit(self, px: f64, py: f64) -> bool {
        px >= self.x && px < self.x + self.w && py >= self.y && py < self.y + self.h
    }
    #[inline]
    fn pad(self, t: f64, r: f64, b: f64, l: f64) -> Rect {
        Rect { x: self.x+l, y: self.y+t, w: self.w-l-r, h: self.h-t-b }
    }
}

// ─── Spring physics (ved runtime) ────────────────────────────────────────────
#[derive(Clone, Copy)]
struct Spring { x: f64, v: f64, k: f64, d: f64, m: f64 }
impl Spring {
    fn new(k: f64, d: f64, m: f64) -> Self { Self { x: 0.0, v: 0.0, k, d, m } }
    /// Step toward target. Returns true when settled.
    fn tick(&mut self, target: f64, dt: f64) -> bool {
        let a = (-self.k * (self.x - target) - self.d * self.v) / self.m;
        self.v += a * dt;
        self.x += self.v * dt;
        (self.x - target).abs() < 0.001 && self.v.abs() < 0.001
    }
}

// ─── User-defined shapes ─────────────────────────────────────────────────────


// ─── Think (helper) functions ─────────────────────────────────────────────────


// ─── App state (from VED `remember` declarations) ────────────────────────────
struct AppState {
    screen: u32,
    counter_count: i64,
}

impl AppState {
    fn new() -> Self {
        Self {
            screen: 0,
            counter_count: 0,
        }
    }
}


// ─── Global singletons (WASM is single-threaded) ─────────────────────────────
static mut VED_W: f64 = 800.0;
static mut VED_H: f64 = 600.0;
static mut VED_STATE: Option<AppState> = None;
static mut VED_TAPS:  Vec<(Rect, u32)> = Vec::new();
// Hover spring registry: (tap_id, spring[0→1], target[0 or 1], max_scale)
static mut VED_HOVER: Vec<(u32, Spring, f64, f64)> = Vec::new();
static mut VED_HOVERED: i32 = -1;

#[inline] fn vw() -> f64 { unsafe { VED_W } }
#[inline] fn vh() -> f64 { unsafe { VED_H } }
#[inline] fn st() -> &'static mut AppState { unsafe { VED_STATE.as_mut().unwrap_unchecked() } }
#[inline] fn push_tap(r: Rect, id: u32) { unsafe { VED_TAPS.push((r, id)) } }
// Ensure a hover spring exists for this tap (called from render before push_tap)
fn ensure_hover(id: u32, max_scale: f64) {
    unsafe {
        if !VED_HOVER.iter().any(|(hid, _, _, _)| *hid == id) {
            VED_HOVER.push((id, Spring::new(300.0, 25.0, 1.0), 0.0, max_scale));
        }
    }
}
// Return current animated scale for a tap (1.0 when not hovered/settled)
fn hover_scale(id: u32) -> f64 {
    unsafe {
        VED_HOVER.iter()
            .find(|(hid, _, _, _)| *hid == id)
            .map(|(_, s, _, ms)| 1.0 + s.x * (ms - 1.0))
            .unwrap_or(1.0)
    }
}

// ─── Screen / piece render functions (generated from VED AST) ────────────────
fn render_counter() {
    let _count = st().counter_count ;
    // — layout scope —
    let __pb = Rect { x: 0.0, y: 0.0, w: vw(), h: vh() };
    v_fill("#0a0a0a"); if 0.0 > 0.0 { v_rrect(__pb.x, __pb.y, __pb.w, __pb.h, 0.0); } else { v_rect(__pb.x, __pb.y, __pb.w, __pb.h); }
    // measure children
    v_font("700 96px system-ui, sans-serif");
    let __c0_text = alloc::borrow::Cow::Owned(format!("{}", st().counter_count));
    let __c0_w = v_measure(&__c0_text);
    let __c0_h = 134.4;
    let __c1_w = __pb.w;
    v_font("600 17px system-ui, sans-serif");
    let __c1_m0_text = alloc::borrow::Cow::Borrowed("−");
    let __c1_m0_w = (v_measure(&__c1_m0_text) + 24.0 * 2.0).max(80.0);
    let __c1_m0_h = 23.8 + 16.0 * 2.0;
    v_font("600 17px system-ui, sans-serif");
    let __c1_m1_text = alloc::borrow::Cow::Borrowed("+");
    let __c1_m1_w = (v_measure(&__c1_m1_text) + 24.0 * 2.0).max(80.0);
    let __c1_m1_h = 23.8 + 16.0 * 2.0;
    let __c1_h = __c1_m0_h + __c1_m1_h + 16.0 * 1.0 + 0.0;
    v_font("400 12px system-ui, sans-serif");
    let __c2_text = alloc::borrow::Cow::Borrowed("Tap buttons to animate");
    let __c2_w = v_measure(&__c2_text);
    let __c2_h = 16.8;
    let __total_h = __c0_h + __c1_h + __c2_h + 24.0 * 2.0;
    let __total_w = [__c0_w, __c1_w, __c2_w].iter().cloned().fold(0.0f64, f64::max);
    let __col_x = __pb.x + (__pb.w - __total_w) / 2.0;
    let mut __col_y = __pb.y + (__pb.h - __total_h) / 2.0;
    let __c0_rect = Rect { x: __col_x + (__total_w - __c0_w) / 2.0, y: __col_y, w: __c0_w, h: __c0_h };
    { let __pb = __c0_rect;
        // words
        v_font("700 96px system-ui, -apple-system, sans-serif");
        v_fill("#7f6fe8");
        let __wt = alloc::borrow::Cow::Owned(format!("{}", st().counter_count));
        let __ww = v_measure(&__wt);
        let __wx = __pb.x + (__pb.w - __ww) / 2.0;
        v_text(&__wt, __wx, __pb.y + 96.0 * 1.2);
    }
    __col_y += __c0_h + 24.0;
    let __c1_rect = Rect { x: __col_x + (__total_w - __c1_w) / 2.0, y: __col_y, w: __c1_w, h: __c1_h };
    { let __pb = __c1_rect;
        // measure children
        v_font("600 17px system-ui, sans-serif");
        let __c0_text = alloc::borrow::Cow::Borrowed("−");
        let __c0_w = (v_measure(&__c0_text) + 24.0 * 2.0).max(80.0);
        let __c0_h = 23.8 + 16.0 * 2.0;
        v_font("600 17px system-ui, sans-serif");
        let __c1_text = alloc::borrow::Cow::Borrowed("+");
        let __c1_w = (v_measure(&__c1_text) + 24.0 * 2.0).max(80.0);
        let __c1_h = 23.8 + 16.0 * 2.0;
        let __total_h = __c0_h + __c1_h + 16.0 * 1.0;
        let __total_w = [__c0_w, __c1_w].iter().cloned().fold(0.0f64, f64::max);
        let __col_x = __pb.x;
        let mut __col_y = __pb.y;
        let __c0_rect = Rect { x: __col_x + (__total_w - __c0_w) / 2.0, y: __col_y, w: __c0_w, h: __c0_h };
        { let __pb = __c0_rect;
            // tap
            v_font("600 17px system-ui, -apple-system, sans-serif");
            let __tl = alloc::borrow::Cow::Borrowed("−");
            let __tw = v_measure(&__tl);
            let __tbw = (__tw + 24.0 * 2.0).max(80.0);
            let __tbh = 17.0 * 1.4 + 16.0 * 2.0;
            let __tx = __pb.x + (__pb.w - __tbw) / 2.0;
            let __ty = __pb.y;
            ensure_hover(0, 1.0500);
            let __hs = hover_scale(0);
            unsafe { ved_push_transform(__tx + __tbw / 2.0, __ty + __tbh / 2.0, __hs, __hs); }
            v_fill("#333");
            v_rrect(__tx, __ty, __tbw, __tbh, 12.0);
            v_fill("white");
            v_text(&__tl, __tx + (__tbw - __tw) / 2.0, __ty + 17.0 * 1.2 + 16.0);
            unsafe { ved_pop_transform(); }
            push_tap(Rect { x: __tx, y: __ty, w: __tbw, h: __tbh }, 0);
        }
        __col_y += __c0_h + 16.0;
        let __c1_rect = Rect { x: __col_x + (__total_w - __c1_w) / 2.0, y: __col_y, w: __c1_w, h: __c1_h };
        { let __pb = __c1_rect;
            // tap
            v_font("600 17px system-ui, -apple-system, sans-serif");
            let __tl = alloc::borrow::Cow::Borrowed("+");
            let __tw = v_measure(&__tl);
            let __tbw = (__tw + 24.0 * 2.0).max(80.0);
            let __tbh = 17.0 * 1.4 + 16.0 * 2.0;
            let __tx = __pb.x + (__pb.w - __tbw) / 2.0;
            let __ty = __pb.y;
            ensure_hover(1, 1.0500);
            let __hs = hover_scale(1);
            unsafe { ved_push_transform(__tx + __tbw / 2.0, __ty + __tbh / 2.0, __hs, __hs); }
            v_fill("#7f6fe8");
            v_rrect(__tx, __ty, __tbw, __tbh, 12.0);
            v_fill("white");
            v_text(&__tl, __tx + (__tbw - __tw) / 2.0, __ty + 17.0 * 1.2 + 16.0);
            unsafe { ved_pop_transform(); }
            push_tap(Rect { x: __tx, y: __ty, w: __tbw, h: __tbh }, 1);
        }
    }
    __col_y += __c1_h + 24.0;
    let __c2_rect = Rect { x: __col_x + (__total_w - __c2_w) / 2.0, y: __col_y, w: __c2_w, h: __c2_h };
    { let __pb = __c2_rect;
        // words
        v_font("400 12px system-ui, -apple-system, sans-serif");
        v_fill("#444");
        let __wt = alloc::borrow::Cow::Borrowed("Tap buttons to animate");
        let __ww = v_measure(&__wt);
        let __wx = __pb.x + (__pb.w - __ww) / 2.0;
        v_text(&__wt, __wx, __pb.y + 12.0 * 1.2);
    }
}




// ─── Tap action dispatch (generated from VED `on tap` bodies) ────────────────
fn dispatch(id: u32) {
    match id {
        0 => {
            st().counter_count = (st().counter_count - 1);
        }
        1 => {
            st().counter_count = (st().counter_count + 1);
        }

        _ => {}
    }
}

// ─── Render dispatcher ───────────────────────────────────────────────────────
fn do_render() {
    unsafe { VED_TAPS.clear(); }
    unsafe { ved_clear(10, 10, 10); }
    render_counter();
}

// ─── WASM exports (called from the VED HTML bootstrap) ───────────────────────

#[no_mangle]
pub extern "C" fn ved_init(w: f64, h: f64) {
    unsafe {
        VED_W = w; VED_H = h;
        VED_STATE = Some(AppState::new());
        VED_TAPS    = Vec::new();
        VED_HOVER   = Vec::new();
        VED_HOVERED = -1;
    }
    do_render();
}

#[no_mangle]
pub extern "C" fn ved_resize(w: f64, h: f64) {
    unsafe { VED_W = w; VED_H = h; }
    // Guard: do not render before ved_init has set up AppState
    if unsafe { VED_STATE.is_some() } {
        do_render();
    }
}

#[no_mangle]
pub extern "C" fn ved_tap(x: f64, y: f64) {
    let snap: Vec<(Rect, u32)> = unsafe { VED_TAPS.clone() };
    for (rect, id) in snap {
        if rect.hit(x, y) {
            dispatch(id);
            do_render();
            return;
        }
    }
}

#[no_mangle]
pub extern "C" fn ved_hover(x: f64, y: f64) {
    let taps: Vec<(Rect, u32)> = unsafe { VED_TAPS.clone() };
    let mut new_hovered: i32 = -1;
    for (rect, id) in &taps {
        if rect.hit(x, y) { new_hovered = *id as i32; break; }
    }
    let old_hovered = unsafe { VED_HOVERED };
    if new_hovered != old_hovered {
        unsafe { VED_HOVERED = new_hovered; }
        // Update spring targets: 1.0 for hovered, 0.0 for all others
        unsafe {
            for (hid, _, target, _) in VED_HOVER.iter_mut() {
                *target = if *hid as i32 == new_hovered { 1.0 } else { 0.0 };
            }
        }
        unsafe { ved_request_frame(); }
    }
}

#[no_mangle]
pub extern "C" fn ved_frame() {
    let dt = 1.0_f64 / 60.0;
    let mut animating = false;
    unsafe {
        for (_, spring, target, _) in VED_HOVER.iter_mut() {
            let settled = spring.tick(*target, dt);
            if !settled { animating = true; }
        }
    }
    do_render();
    if animating {
        unsafe { ved_request_frame(); }
    }
}
