use crate::ast::*;
use crate::compiler::{emit_stmt, rust_ident, CompileResult};
use std::path::Path;
use std::process::Command;

/// Emit native binary target
pub fn emit(program: Program, out: &Path, release: bool) -> CompileResult<()> {
    // Generate Rust code as intermediate representation
    let rust_code = generate_rust_code(&program)?;

    let rs_path = out.join("main.rs");
    std::fs::write(&rs_path, rust_code).map_err(|e| crate::compiler::CompileError {
        message: format!("Failed to write main.rs: {}", e),
        span: (0..0).into(),
    })?;

    // Compile with rustc
    let output_path = out.join(if cfg!(windows) { "app.exe" } else { "app" });

    let mut cmd = Command::new("rustc");
    cmd.arg(&rs_path).arg("-o").arg(&output_path);

    if release {
        cmd.arg("-C").arg("opt-level=3");
        cmd.arg("-C").arg("lto=fat");
        cmd.arg("-C").arg("codegen-units=1");
    } else {
        cmd.arg("-C").arg("opt-level=0");
        cmd.arg("-C").arg("debuginfo=2");
    }

    let output = cmd.output().map_err(|e| crate::compiler::CompileError {
        message: format!("Failed to run rustc: {}", e),
        span: (0..0).into(),
    })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(crate::compiler::CompileError {
            message: format!("Rust compilation failed:\n{}", stderr),
            span: (0..0).into(),
        });
    }

    println!(
        "  bin  ->  {}/{}",
        out.display(),
        output_path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
    );
    Ok(())
}

fn generate_rust_code(program: &Program) -> CompileResult<String> {
    let mut code = String::new();

    // Header
    code.push_str("// Auto-generated by VED compiler\n");
    code.push_str("// Do not edit manually\n\n");
    code.push_str("use std::collections::HashMap;\n\n");

    // Generate struct definitions
    for item in &program.items {
        if let Item::Shape(s) = item {
            code.push_str(&generate_shape(s));
        }
    }

    // Generate function definitions
    for item in &program.items {
        if let Item::Think(t) = item {
            code.push_str(&generate_think(t)?);
        }
    }

    // Generate main function
    code.push_str("fn main() {\n");
    code.push_str("    println!(\"VED Native Application\");\n");

    // Call main think if it exists
    for item in &program.items {
        if let Item::Think(t) = item {
            if t.name == "main" {
                code.push_str("    let _ = main_think();\n");
            }
        }
    }

    code.push_str("}\n");

    Ok(code)
}

fn generate_shape(shape: &ShapeDef) -> String {
    let mut code = String::new();

    code.push_str("#[derive(Debug, Clone)]\n");
    code.push_str(&format!("struct {} {{\n", sanitize_ident(&shape.name)));

    for field in &shape.fields {
        let ty = type_to_rust(&field.ty);
        code.push_str(&format!("    {}: {},\n", sanitize_ident(&field.name), ty));
    }

    code.push_str("}\n\n");

    // Constructor
    code.push_str(&format!("impl {} {{\n", sanitize_ident(&shape.name)));
    code.push_str("    fn new(");

    for (i, field) in shape.fields.iter().enumerate() {
        if i > 0 {
            code.push_str(", ");
        }
        let ty = type_to_rust(&field.ty);
        code.push_str(&format!("{}: {}", sanitize_ident(&field.name), ty));
    }

    code.push_str(") -> Self {\n");
    code.push_str("        Self {\n");

    for field in &shape.fields {
        code.push_str(&format!(
            "            {}: {},\n",
            sanitize_ident(&field.name),
            sanitize_ident(&field.name)
        ));
    }

    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code
}

fn generate_think(think: &ThinkDef) -> CompileResult<String> {
    let mut code = String::new();

    let fn_name = if think.name == "main" {
        "main_think".to_string()
    } else {
        sanitize_ident(&think.name)
    };

    // Function signature
    let params: Vec<String> = think
        .params
        .iter()
        .map(|p| format!("{}: {}", sanitize_ident(&p.name), type_to_rust(&p.ty)))
        .collect();

    let ret_ty = think
        .ret
        .as_ref()
        .map(type_to_rust)
        .unwrap_or_else(|| "()".to_string());

    let is_async = think.is_async;
    let async_kw = if is_async { "async " } else { "" };

    code.push_str(&format!(
        "{}fn {}({}) -> {} {{\n",
        async_kw,
        fn_name,
        params.join(", "),
        ret_ty
    ));

    if think.body.is_empty() {
        code.push_str("    ()\n");
    } else {
        for stmt in &think.body {
            let line = emit_stmt(stmt, 1);
            code.push_str(&line);
            code.push('\n');
        }
    }

    code.push_str("}\n\n");
    Ok(code)
}

fn type_to_rust(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Num => "i64".to_string(),
        TypeExpr::Dec => "f64".to_string(),
        TypeExpr::Text => "String".to_string(),
        TypeExpr::Bool => "bool".to_string(),
        TypeExpr::Nothing => "()".to_string(),
        TypeExpr::List(t) => format!("Vec<{}>", type_to_rust(t)),
        TypeExpr::Map(k, v) => format!("HashMap<{}, {}>", type_to_rust(k), type_to_rust(v)),
        TypeExpr::Maybe(t) => format!("Option<{}>", type_to_rust(t)),
        TypeExpr::Ok(t, e) => format!("Result<{}, {}>", type_to_rust(t), type_to_rust(e)),
        TypeExpr::Named(n) => sanitize_ident(n),
        TypeExpr::Any => "Box<dyn std::any::Any>".to_string(),
        TypeExpr::Function(params, ret) => {
            let param_types: Vec<String> = params.iter().map(type_to_rust).collect();
            format!("fn({}) -> {}", param_types.join(", "), type_to_rust(ret))
        }
    }
}

fn sanitize_ident(name: &str) -> String {
    rust_ident(name)
}
