use crate::ast::*;
use crate::compiler::{emit_expr, emit_stmt, CompileResult};
use std::path::Path;

// ─── Public entry point ───────────────────────────────────────────────────────

pub fn emit(program: Program, out: &Path, release: bool) -> CompileResult<()> {
    std::fs::create_dir_all(out).map_err(|e| crate::compiler::CompileError {
        message: format!("Failed to create output dir: {}", e),
        span: (0..0).into(),
    })?;

    // Derive lib name before program is moved
    let lib_name = find_main_screen(&program)
        .map(|s| s.name.to_lowercase().replace('-', "_"))
        .unwrap_or_else(|| "ved_app".to_string());

    // 1. HTML bootstrap (replaces browser, wires WASM imports)
    let html = generate_html_bootstrap(&program);
    write_file(out.join("index.html"), &html)?;

    // 2. Cargo.toml for the WASM project
    let cargo_toml = generate_wasm_cargo_toml(&program);
    write_file(out.join("Cargo.toml"), &cargo_toml)?;

    // 3. Rust source that compiles to app.wasm
    let src_dir = out.join("src");
    std::fs::create_dir_all(&src_dir).map_err(|e| crate::compiler::CompileError {
        message: format!("Failed to create src dir: {}", e),
        span: (0..0).into(),
    })?;

    let rust_src = generate_wasm_source(&program);
    write_file(src_dir.join("lib.rs"), &rust_src)?;

    // 4. Ghost intents artifact (unchanged)
    let intents = generate_ghost_intents(&program);
    if !intents.is_empty() {
        write_file(out.join("ghost-intents.json"), &intents)?;
    }

    println!("  web  ->  {}/src/lib.rs", out.display());

    // 5. Invoke cargo to compile the generated Rust to WASM
    let profile = if release { "release" } else { "debug" };
    let mut cargo_args = vec!["build", "--target", "wasm32-unknown-unknown"];
    if release {
        cargo_args.push("--release");
    }

    match std::process::Command::new("cargo")
        .args(&cargo_args)
        .current_dir(out)
        .status()
    {
        Ok(status) if status.success() => {
            let wasm_src = out.join(format!(
                "target/wasm32-unknown-unknown/{}/{}.wasm",
                profile, lib_name
            ));
            if wasm_src.exists() {
                std::fs::copy(&wasm_src, out.join("app.wasm")).map_err(|e| {
                    crate::compiler::CompileError {
                        message: format!("Failed to copy app.wasm: {}", e),
                        span: (0..0).into(),
                    }
                })?;
                println!("  wasm ->  {}/app.wasm", out.display());
            } else {
                eprintln!(
                    "  warning: cargo succeeded but {} not found",
                    wasm_src.display()
                );
            }
        }
        Ok(status) => {
            eprintln!(
                "  warning: WASM build failed (exit {}). Ensure the wasm32-unknown-unknown target is installed:",
                status
            );
            eprintln!("    rustup target add wasm32-unknown-unknown");
        }
        Err(e) => {
            eprintln!("  warning: could not invoke cargo ({})", e);
            eprintln!(
                "  To build WASM manually: cd {} && cargo build --target wasm32-unknown-unknown",
                out.display()
            );
        }
    }

    Ok(())
}

// ─── HTML bootstrap ───────────────────────────────────────────────────────────
// This is NOT a JS framework. It is a thin WASM import adapter:
// browser canvas API → WASM imports that the generated Rust calls.
// ~40 lines, never written by the VED developer.

pub(crate) fn generate_html_bootstrap(program: &Program) -> String {
    let title = find_main_screen(program)
        .map(|s| s.name.clone())
        .unwrap_or_else(|| "VED App".to_string());

    let bg = find_main_screen(program)
        .and_then(|s| s.children.first())
        .and_then(|n| {
            if let UiNode::Box(b) = n {
                b.props.color.as_ref().map(color_to_css)
            } else {
                None
            }
        })
        .unwrap_or_else(|| "#0a0a0a".to_string());

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>{title}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
html,body{{width:100%;height:100%;overflow:hidden;background:{bg}}}
canvas{{display:block;width:100vw;height:100vh;touch-action:none}}
#_verr{{display:none;position:fixed;inset:0;z-index:9999;background:#111;color:#f66;padding:28px;font:13px/1.7 monospace;white-space:pre-wrap;overflow:auto}}
</style>
</head>
<body>
<canvas id="v"></canvas>
<div id="_verr"></div>
<script type="module">
/* VED bootstrap — not user code, generated by vedc */
const canvas = document.getElementById('v');
const ctx    = canvas.getContext('2d');
const errDiv = document.getElementById('_verr');
const dec    = new TextDecoder();
let   inst   = null;
let   VW     = window.innerWidth;
let   VH     = window.innerHeight;

const mem  = () => new Uint8Array(inst.exports.memory.buffer);
const str_ = (p,l) => dec.decode(mem().subarray(p, p+l));

function showErr(e) {{
  errDiv.style.display = 'block';
  errDiv.textContent   = 'VED boot error\n\n' + e;
}}

/* Browser API ← WASM imports (canvas 2D + frame + input) */
const imports = {{ env: {{
  ved_clear      : (r,g,b)           => {{ ctx.fillStyle=`rgb(${{r}},${{g}},${{b}})`; ctx.fillRect(0,0,VW,VH); }},
  ved_set_fill   : (p,l)             => {{ ctx.fillStyle = str_(p,l); }},
  ved_set_stroke : (p,l)             => {{ ctx.strokeStyle = str_(p,l); }},
  ved_set_alpha  : (a)               => {{ ctx.globalAlpha = a; }},
  ved_fill_rect  : (x,y,w,h)        => {{ ctx.fillRect(x,y,w,h); }},
  ved_fill_rrect : (x,y,w,h,r)      => {{
    ctx.beginPath();
    ctx.roundRect(x,y,w,h,r);
    ctx.fill();
  }},
  ved_stroke_rrect:(x,y,w,h,r,bw)   => {{
    ctx.lineWidth=bw;
    ctx.beginPath();
    ctx.roundRect(x,y,w,h,r);
    ctx.stroke();
  }},
  ved_set_shadow : (bl,ox,oy,p,l)   => {{ ctx.shadowBlur=bl; ctx.shadowOffsetX=ox; ctx.shadowOffsetY=oy; ctx.shadowColor=str_(p,l); }},
  ved_clear_shadow: ()               => {{ ctx.shadowBlur=0; ctx.shadowOffsetX=0; ctx.shadowOffsetY=0; ctx.shadowColor='transparent'; }},
  ved_set_font   : (p,l)            => {{ ctx.font=str_(p,l); ctx.textBaseline='alphabetic'; }},
  ved_fill_text  : (p,l,x,y)        => {{ ctx.fillText(str_(p,l),x,y); }},
  ved_measure_text:(p,l)            => {{ return ctx.measureText(str_(p,l)).width; }},
  ved_draw_image : (sp,sl,x,y,w,h) => {{
    const src=str_(sp,sl);
    const img=new Image();
    img.onload=()=>{{ ctx.drawImage(img,x,y,w,h); }};
    img.src=src;
  }},
  ved_push_transform: (cx,cy,sx,sy) => {{ ctx.save(); ctx.translate(cx,cy); ctx.scale(sx,sy); ctx.translate(-cx,-cy); }},
  ved_pop_transform:  ()            => {{ ctx.restore(); }},
  ved_request_frame: ()             => {{ requestAnimationFrame(frame); }},
}}
}};

function frame() {{ inst.exports.ved_frame(); }}

function sizeCanvas() {{
  VW = window.innerWidth;
  VH = window.innerHeight;
  canvas.width  = Math.round(VW * devicePixelRatio);
  canvas.height = Math.round(VH * devicePixelRatio);
  ctx.scale(devicePixelRatio, devicePixelRatio);
}}

async function boot() {{
  /* Use arrayBuffer — works with any server MIME type for .wasm */
  const buf = await fetch('./app.wasm').then(r => r.arrayBuffer());
  const {{ instance }} = await WebAssembly.instantiate(buf, imports);
  inst = instance;

  /* Size canvas, then init WASM state (ved_init triggers the first render) */
  sizeCanvas();
  inst.exports.ved_init(VW, VH);

  /* Wire events only after state is initialised */
  window.addEventListener('resize', () => {{
    sizeCanvas();
    inst.exports.ved_resize(VW, VH);
  }});

  canvas.addEventListener('pointerdown', e => {{
    const r = canvas.getBoundingClientRect();
    inst.exports.ved_tap(e.clientX - r.left, e.clientY - r.top);
  }});

  canvas.addEventListener('pointermove', e => {{
    if (inst.exports.ved_hover) {{
      const r = canvas.getBoundingClientRect();
      inst.exports.ved_hover(e.clientX - r.left, e.clientY - r.top);
    }}
  }});

  canvas.addEventListener('pointerleave', () => {{
    if (inst.exports.ved_hover) inst.exports.ved_hover(-1.0, -1.0);
  }});
}}

boot().catch(showErr);
</script>
</body>
</html>
"#,
        title = title,
        bg = bg
    )
}

// ─── Cargo.toml for the WASM project ─────────────────────────────────────────

fn generate_wasm_cargo_toml(program: &Program) -> String {
    let name = find_main_screen(program)
        .map(|s| s.name.to_lowercase())
        .unwrap_or_else(|| "ved_app".to_string());

    format!(
        r#"[package]
name = "ved-app"
version = "0.1.0"
edition = "2021"

# VED-compiled WASM — build: cargo build --target wasm32-unknown-unknown --release

[lib]
name = "{name}"
crate-type = ["cdylib"]

[dependencies]
wee_alloc = "0.4"

[profile.release]
opt-level = "z"
lto        = true
codegen-units = 1
strip      = true
panic      = "abort"
"#,
        name = name.replace('-', "_")
    )
}

// ─── Main Rust source generator ──────────────────────────────────────────────

pub(crate) fn generate_wasm_source(program: &Program) -> String {
    let screens: Vec<&ScreenDef> = program
        .items
        .iter()
        .filter_map(|i| {
            if let Item::Screen(s) = i {
                Some(s)
            } else {
                None
            }
        })
        .collect();

    let pieces: Vec<&PieceDef> = program
        .items
        .iter()
        .filter_map(|i| {
            if let Item::Piece(p) = i {
                Some(p)
            } else {
                None
            }
        })
        .collect();

    let shapes: Vec<&ShapeDef> = program
        .items
        .iter()
        .filter_map(|i| {
            if let Item::Shape(s) = i {
                Some(s)
            } else {
                None
            }
        })
        .collect();

    let thinks: Vec<&ThinkDef> = program
        .items
        .iter()
        .filter_map(|i| {
            if let Item::Think(t) = i {
                Some(t)
            } else {
                None
            }
        })
        .collect();

    let mut tap_id: u32 = 0;
    let mut tap_actions: Vec<TapAction> = Vec::new();

    // Generate screen render functions
    let screen_render_fns: Vec<String> = screens
        .iter()
        .map(|s| emit_screen_render_fn(s, &mut tap_id, &mut tap_actions))
        .collect();

    // Generate piece render functions
    let piece_render_fns: Vec<String> = pieces
        .iter()
        .map(|p| emit_piece_render_fn(p, &mut tap_id, &mut tap_actions))
        .collect();

    // Generate AppState struct from all screen state
    let state_struct = emit_state_struct(&screens);

    // Generate tap dispatch
    let tap_dispatch = emit_tap_dispatch(&tap_actions);

    // Generate render dispatch
    let render_dispatch = emit_render_dispatch(&screens);

    // Generate think helper functions (after screen/piece tap IDs are assigned)
    let mut think_fns: Vec<String> = Vec::new();
    for t in &thinks {
        think_fns.push(emit_think_fn(t, &mut tap_id, &mut tap_actions));
    }

    // Generate shape structs
    let shape_structs: Vec<String> = shapes.iter().map(|s| emit_shape_struct(s)).collect();

    format!(
        r#"// VED App — generated by vedc. Do not edit.
// Target: wasm32-unknown-unknown (pure WASM, no JS framework)
#![allow(dead_code, unused_variables, non_upper_case_globals, static_mut_refs, unused_mut, unused_must_use, unused_imports)]
#![no_std]

extern crate alloc;
use alloc::{{string::String, vec::Vec, format}};

// ─── allocator (required for no_std + alloc) ─────────────────────────────────
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {{ loop {{}} }}

// ─── Canvas / browser API imports (provided by the VED HTML bootstrap) ────────
extern "C" {{
    fn ved_clear(r: u8, g: u8, b: u8);
    fn ved_set_fill(ptr: *const u8, len: u32);
    fn ved_set_stroke(ptr: *const u8, len: u32);
    fn ved_set_alpha(a: f64);
    fn ved_fill_rect(x: f64, y: f64, w: f64, h: f64);
    fn ved_fill_rrect(x: f64, y: f64, w: f64, h: f64, r: f64);
    fn ved_stroke_rrect(x: f64, y: f64, w: f64, h: f64, r: f64, bw: f64);
    fn ved_set_shadow(blur: f64, ox: f64, oy: f64, c_ptr: *const u8, c_len: u32);
    fn ved_clear_shadow();
    fn ved_set_font(ptr: *const u8, len: u32);
    fn ved_fill_text(ptr: *const u8, len: u32, x: f64, y: f64);
    fn ved_measure_text(ptr: *const u8, len: u32) -> f64;
    fn ved_draw_image(src_ptr: *const u8, src_len: u32, x: f64, y: f64, w: f64, h: f64);
    fn ved_push_transform(cx: f64, cy: f64, sx: f64, sy: f64);
    fn ved_pop_transform();
    fn ved_request_frame();
}}

// ─── String bridge: pass &str to JS without allocator overhead ───────────────
static mut STR_BUF: [u8; 8192] = [0u8; 8192];
unsafe fn with_str<R, F: Fn(*const u8, u32) -> R>(s: &str, f: F) -> R {{
    let b = s.as_bytes();
    let n = if b.len() < STR_BUF.len() {{ b.len() }} else {{ STR_BUF.len() - 1 }};
    let dst = &mut STR_BUF[..n];
    dst.copy_from_slice(&b[..n]);
    f(STR_BUF.as_ptr(), n as u32)
}}

// ─── Canvas helpers ───────────────────────────────────────────────────────────
#[inline] fn v_fill(c: &str)      {{ unsafe {{ with_str(c, |p,l| ved_set_fill(p,l)) }} }}
#[inline] fn v_stroke(c: &str)    {{ unsafe {{ with_str(c, |p,l| ved_set_stroke(p,l)) }} }}
#[inline] fn v_font(f: &str)      {{ unsafe {{ with_str(f, |p,l| ved_set_font(p,l)) }} }}
#[inline] fn v_rect(x:f64,y:f64,w:f64,h:f64)        {{ unsafe {{ ved_fill_rect(x,y,w,h) }} }}
#[inline] fn v_rrect(x:f64,y:f64,w:f64,h:f64,r:f64) {{ unsafe {{ ved_fill_rrect(x,y,w,h,r) }} }}
#[inline] fn v_brect(x:f64,y:f64,w:f64,h:f64,r:f64,bw:f64) {{ unsafe {{ ved_stroke_rrect(x,y,w,h,r,bw) }} }}
#[inline] fn v_text(s:&str,x:f64,y:f64) {{ unsafe {{ with_str(s,|p,l| ved_fill_text(p,l,x,y)) }} }}
#[inline] fn v_measure(s:&str) -> f64   {{ unsafe {{ with_str(s,|p,l| ved_measure_text(p,l)) }} }}
#[inline] fn v_image(src:&str,x:f64,y:f64,w:f64,h:f64) {{
    unsafe {{ with_str(src, |p,l| ved_draw_image(p,l,x,y,w,h)) }}
}}
#[inline] fn v_shadow(blur:f64,ox:f64,oy:f64,c:&str) {{
    unsafe {{ with_str(c, |p,l| ved_set_shadow(blur,ox,oy,p,l)) }}
}}
#[inline] fn v_clear_shadow() {{ unsafe {{ ved_clear_shadow() }} }}
#[inline] fn v_alpha(a:f64)   {{ unsafe {{ ved_set_alpha(a) }} }}

// ─── Layout rect ─────────────────────────────────────────────────────────────
#[derive(Clone, Copy, Debug)]
struct Rect {{ x: f64, y: f64, w: f64, h: f64 }}
impl Rect {{
    #[inline]
    fn hit(self, px: f64, py: f64) -> bool {{
        px >= self.x && px < self.x + self.w && py >= self.y && py < self.y + self.h
    }}
    #[inline]
    fn pad(self, t: f64, r: f64, b: f64, l: f64) -> Rect {{
        Rect {{ x: self.x+l, y: self.y+t, w: self.w-l-r, h: self.h-t-b }}
    }}
}}

// ─── Spring physics (ved runtime) ────────────────────────────────────────────
#[derive(Clone, Copy)]
struct Spring {{ x: f64, v: f64, k: f64, d: f64, m: f64 }}
impl Spring {{
    fn new(k: f64, d: f64, m: f64) -> Self {{ Self {{ x: 0.0, v: 0.0, k, d, m }} }}
    /// Step toward target. Returns true when settled.
    fn tick(&mut self, target: f64, dt: f64) -> bool {{
        let a = (-self.k * (self.x - target) - self.d * self.v) / self.m;
        self.v += a * dt;
        self.x += self.v * dt;
        (self.x - target).abs() < 0.001 && self.v.abs() < 0.001
    }}
}}

// ─── User-defined shapes ─────────────────────────────────────────────────────
{shape_structs}

// ─── Think (helper) functions ─────────────────────────────────────────────────
{think_fns}

// ─── App state (from VED `remember` declarations) ────────────────────────────
{state_struct}

// ─── Global singletons (WASM is single-threaded) ─────────────────────────────
static mut VED_W: f64 = 800.0;
static mut VED_H: f64 = 600.0;
static mut VED_STATE: Option<AppState> = None;
static mut VED_TAPS:  Vec<(Rect, u32)> = Vec::new();
// Hover spring registry: (tap_id, spring[0→1], target[0 or 1], max_scale)
static mut VED_HOVER: Vec<(u32, Spring, f64, f64)> = Vec::new();
static mut VED_HOVERED: i32 = -1;

#[inline] fn vw() -> f64 {{ unsafe {{ VED_W }} }}
#[inline] fn vh() -> f64 {{ unsafe {{ VED_H }} }}
#[inline] fn st() -> &'static mut AppState {{ unsafe {{ VED_STATE.as_mut().unwrap_unchecked() }} }}
#[inline] fn push_tap(r: Rect, id: u32) {{ unsafe {{ VED_TAPS.push((r, id)) }} }}
// Ensure a hover spring exists for this tap (called from render before push_tap)
fn ensure_hover(id: u32, max_scale: f64) {{
    unsafe {{
        if !VED_HOVER.iter().any(|(hid, _, _, _)| *hid == id) {{
            VED_HOVER.push((id, Spring::new(300.0, 25.0, 1.0), 0.0, max_scale));
        }}
    }}
}}
// Return current animated scale for a tap (1.0 when not hovered/settled)
fn hover_scale(id: u32) -> f64 {{
    unsafe {{
        VED_HOVER.iter()
            .find(|(hid, _, _, _)| *hid == id)
            .map(|(_, s, _, ms)| 1.0 + s.x * (ms - 1.0))
            .unwrap_or(1.0)
    }}
}}

// ─── Screen / piece render functions (generated from VED AST) ────────────────
{screen_render_fns}

{piece_render_fns}

// ─── Tap action dispatch (generated from VED `on tap` bodies) ────────────────
fn dispatch(id: u32) {{
    match id {{
{tap_dispatch}
        _ => {{}}
    }}
}}

// ─── Render dispatcher ───────────────────────────────────────────────────────
fn do_render() {{
    unsafe {{ VED_TAPS.clear(); }}
    {render_dispatch}
}}

// ─── WASM exports (called from the VED HTML bootstrap) ───────────────────────

#[no_mangle]
pub extern "C" fn ved_init(w: f64, h: f64) {{
    unsafe {{
        VED_W = w; VED_H = h;
        VED_STATE = Some(AppState::new());
        VED_TAPS    = Vec::new();
        VED_HOVER   = Vec::new();
        VED_HOVERED = -1;
    }}
    do_render();
}}

#[no_mangle]
pub extern "C" fn ved_resize(w: f64, h: f64) {{
    unsafe {{ VED_W = w; VED_H = h; }}
    // Guard: do not render before ved_init has set up AppState
    if unsafe {{ VED_STATE.is_some() }} {{
        do_render();
    }}
}}

#[no_mangle]
pub extern "C" fn ved_tap(x: f64, y: f64) {{
    let snap: Vec<(Rect, u32)> = unsafe {{ VED_TAPS.clone() }};
    for (rect, id) in snap {{
        if rect.hit(x, y) {{
            dispatch(id);
            do_render();
            return;
        }}
    }}
}}

#[no_mangle]
pub extern "C" fn ved_hover(x: f64, y: f64) {{
    let taps: Vec<(Rect, u32)> = unsafe {{ VED_TAPS.clone() }};
    let mut new_hovered: i32 = -1;
    for (rect, id) in &taps {{
        if rect.hit(x, y) {{ new_hovered = *id as i32; break; }}
    }}
    let old_hovered = unsafe {{ VED_HOVERED }};
    if new_hovered != old_hovered {{
        unsafe {{ VED_HOVERED = new_hovered; }}
        // Update spring targets: 1.0 for hovered, 0.0 for all others
        unsafe {{
            for (hid, _, target, _) in VED_HOVER.iter_mut() {{
                *target = if *hid as i32 == new_hovered {{ 1.0 }} else {{ 0.0 }};
            }}
        }}
        unsafe {{ ved_request_frame(); }}
    }}
}}

#[no_mangle]
pub extern "C" fn ved_frame() {{
    let dt = 1.0_f64 / 60.0;
    let mut animating = false;
    unsafe {{
        for (_, spring, target, _) in VED_HOVER.iter_mut() {{
            let settled = spring.tick(*target, dt);
            if !settled {{ animating = true; }}
        }}
    }}
    do_render();
    if animating {{
        unsafe {{ ved_request_frame(); }}
    }}
}}
"#,
        shape_structs = shape_structs.join("\n"),
        think_fns = think_fns.join("\n"),
        state_struct = state_struct,
        screen_render_fns = screen_render_fns.join("\n"),
        piece_render_fns = piece_render_fns.join("\n"),
        tap_dispatch = tap_dispatch,
        render_dispatch = render_dispatch,
    )
}

// ─── State struct generation ──────────────────────────────────────────────────

fn emit_state_struct(screens: &[&ScreenDef]) -> String {
    let mut fields = String::new();
    let mut inits = String::new();

    fields.push_str("    screen: u32,\n");
    inits.push_str("            screen: 0,\n");

    for screen in screens {
        let prefix = screen.name.to_lowercase();
        for decl in &screen.state {
            let rust_ty = state_ty(&decl.ty);
            let init_val = state_init_expr(&decl.default);
            fields.push_str(&format!("    {}_{}: {},\n", prefix, decl.name, rust_ty));
            inits.push_str(&format!(
                "            {}_{}: {},\n",
                prefix, decl.name, init_val
            ));
        }
    }

    format!(
        "struct AppState {{\n{}}}\n\nimpl AppState {{\n    fn new() -> Self {{\n        Self {{\n{}        }}\n    }}\n}}\n",
        fields, inits
    )
}

fn state_ty(ty: &Option<TypeExpr>) -> &'static str {
    match ty {
        Some(TypeExpr::Num) => "i64",
        Some(TypeExpr::Dec) => "f64",
        Some(TypeExpr::Bool) => "bool",
        Some(TypeExpr::Text) => "String",
        Some(TypeExpr::List(_)) => "Vec<serde_json::Value>",
        Some(TypeExpr::Named(_)) => "String",
        None => "i64", // default: infer as num
        _ => "i64",
    }
}

fn state_init_expr(expr: &Expr) -> String {
    match expr {
        Expr::Num(n, _) => n.to_string(),
        Expr::Dec(d, _) => format!("{}_f64", d),
        Expr::Bool(b, _) => b.to_string(),
        Expr::Text(parts, _) => {
            let s: String = parts
                .iter()
                .map(|p| match p {
                    TextPart::Literal(s) => s.clone(),
                    _ => String::new(),
                })
                .collect();
            format!("String::from({:?})", s)
        }
        Expr::List(_, _) => "Vec::new()".to_string(),
        _ => "0".to_string(),
    }
}

// ─── Screen / piece render functions ─────────────────────────────────────────

struct TapAction {
    id: u32,
    screen_prefix: String,
    body: Vec<Stmt>,
}

fn emit_screen_render_fn(
    screen: &ScreenDef,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
) -> String {
    let fname = screen.name.to_lowercase();
    let prefix = screen.name.to_lowercase();

    let mut body = String::new();

    // Bind state vars as local immutable copies for use in expressions
    for decl in &screen.state {
        body.push_str(&format!(
            "    let _{} = st().{}_{} ;\n",
            decl.name, prefix, decl.name
        ));
    }

    // Emit the UI nodes
    let node_code = emit_nodes(
        &screen.children,
        "Rect { x: 0.0, y: 0.0, w: vw(), h: vh() }",
        &prefix,
        tap_id,
        tap_actions,
        1,
    );
    body.push_str(&node_code);

    // on_load → called once during init (not yet wired, stub)
    format!("fn render_{}() {{\n{}}}\n", fname, body)
}

fn emit_piece_render_fn(
    piece: &PieceDef,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
) -> String {
    let fname = piece.name.to_lowercase();
    let params: Vec<String> = piece
        .needs
        .iter()
        .map(|p| format!("{}: f64", p.name)) // simplified: all params as f64
        .collect();

    let node_code = emit_nodes(
        &piece.children,
        "Rect { x: 0.0, y: 0.0, w: vw(), h: vh() }",
        &fname,
        tap_id,
        tap_actions,
        1,
    );

    format!(
        "fn render_piece_{}({}) {{\n    let _ = ({});\n{}}}\n",
        fname,
        params.join(", "),
        params
            .iter()
            .map(|p| p.split(':').next().unwrap_or("_"))
            .collect::<Vec<_>>()
            .join(", "),
        node_code
    )
}

// ─── UI node code generation ─────────────────────────────────────────────────
// Generates Rust code that, at runtime, measures + lays out + draws each node
// and registers tap areas.

fn emit_nodes(
    nodes: &[UiNode],
    parent_bounds: &str,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    indent: usize,
) -> String {
    let mut out = String::new();
    let pad = "    ".repeat(indent);

    if nodes.is_empty() {
        return out;
    }

    // We generate a scoped block that:
    // 1. Computes sizes for each child (inline, runtime)
    // 2. Lays them out based on parent flow/center/gap
    // 3. Draws each child
    out.push_str(&format!("{}// — layout scope —\n", pad));
    out.push_str(&format!("{}let __pb = {};\n", pad, parent_bounds));

    // Collect node rendering blocks
    let mut child_blocks: Vec<ChildBlock> = Vec::new();

    for node in nodes {
        let block = emit_node_block(node, state_prefix, tap_id, tap_actions, indent);
        child_blocks.push(block);
    }

    // We need to know the parent's flow/gap/center to lay out children.
    // The parent info is available in the BoxNode that called us, but here
    // we get it from the parent context. For the root level, default to column.
    // This is handled in emit_box_node where we know the props.
    for block in &child_blocks {
        out.push_str(&block.code);
    }

    out
}

struct ChildBlock {
    code: String,
}

fn emit_node_block(
    node: &UiNode,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    indent: usize,
) -> ChildBlock {
    let code = match node {
        UiNode::Box(b) => emit_box(b, state_prefix, tap_id, tap_actions, indent),
        UiNode::Words(w) => emit_words(w, state_prefix, indent),
        UiNode::Tap(t) => emit_tap(t, state_prefix, tap_id, tap_actions, indent),
        UiNode::Field(f) => emit_field(f, state_prefix, tap_id, tap_actions, indent),
        UiNode::Image(img) => emit_image(img, state_prefix, indent),
        UiNode::Piece(p) => emit_piece_call(p, state_prefix, indent),
        UiNode::Each(e) => emit_each_node(e, state_prefix, tap_id, tap_actions, indent),
        UiNode::ShowWhen(sw) => emit_show_when(sw, state_prefix, tap_id, tap_actions, indent),
    };
    ChildBlock { code }
}

// ─── Box node ────────────────────────────────────────────────────────────────

fn emit_box(
    node: &BoxNode,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    let mut out = String::new();

    let bounds_var = format!("__box_{}", unique_id(node));

    // Background fill
    if let Some(fill) = &node.props.fill {
        let css = fill_expr_to_css(fill);
        let r = prop_f64(&node.props.radius, 0.0);
        out.push_str(&format!(
            "{}v_fill({:?}); if {:.1} > 0.0 {{ v_rrect(__pb.x, __pb.y, __pb.w, __pb.h, {:.1}); }} else {{ v_rect(__pb.x, __pb.y, __pb.w, __pb.h); }}\n",
            pad, css, r, r
        ));
    }

    // Shadow
    if let Some(shadow) = &node.props.shadow {
        out.push_str(&format!(
            "{}v_shadow({:.1}, {:.1}, {:.1}, {:?}); \n",
            pad, shadow.blur as f64, shadow.x as f64, shadow.y as f64, shadow.color
        ));
    }

    // Border
    if let Some(border) = &node.props.border {
        let r = prop_f64(&node.props.radius, 0.0);
        out.push_str(&format!(
            "{}v_stroke({:?}); v_brect(__pb.x, __pb.y, __pb.w, __pb.h, {:.1}, {:.1});\n",
            pad, border.color, r, border.width as f64
        ));
    }

    if let Some(shadow) = &node.props.shadow {
        let _ = shadow;
        out.push_str(&format!("{}v_clear_shadow();\n", pad));
    }

    if node.children.is_empty() {
        return out;
    }

    // Padding
    let (pt, pr, pb_pad, pl) = if let Some(p) = &node.props.padding {
        (p.top as f64, p.right as f64, p.bottom as f64, p.left as f64)
    } else {
        (0.0, 0.0, 0.0, 0.0)
    };

    if pt > 0.0 || pr > 0.0 || pb_pad > 0.0 || pl > 0.0 {
        out.push_str(&format!(
            "{}let __pb = __pb.pad({:.1}, {:.1}, {:.1}, {:.1});\n",
            pad, pt, pr, pb_pad, pl
        ));
    }

    let flow = node.props.flow.unwrap_or(FlowDir::Down);
    let gap = prop_f64(&node.props.gap, 0.0);
    let center = node.props.center;

    // Generate children with layout
    emit_layout_block(
        &node.children,
        flow,
        gap,
        center,
        state_prefix,
        tap_id,
        tap_actions,
        indent,
        &mut out,
    );

    let _ = bounds_var;
    out
}

#[allow(clippy::too_many_arguments)]
fn emit_layout_block(
    children: &[UiNode],
    flow: FlowDir,
    gap: f64,
    center: Option<CenterDir>,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    indent: usize,
    out: &mut String,
) {
    let pad = "    ".repeat(indent);
    let n = children.len();
    if n == 0 {
        return;
    }

    // Assign a unique var prefix per child so vars don't collide
    let child_vars: Vec<String> = (0..n).map(|i| format!("__c{}", i)).collect();

    // Phase 1: measure each child's intrinsic size
    out.push_str(&format!("{}// measure children\n", pad));
    for (i, child) in children.iter().enumerate() {
        let (mw, mh) = emit_measure(child, state_prefix, &child_vars[i], out, &pad);
        let _ = (mw, mh);
    }

    // Phase 2: compute layout positions
    match flow {
        FlowDir::Down => {
            emit_column_layout(
                children,
                gap,
                center,
                &child_vars,
                out,
                &pad,
                indent,
                state_prefix,
                tap_id,
                tap_actions,
            );
        }
        FlowDir::Across => {
            emit_row_layout(
                children,
                gap,
                center,
                &child_vars,
                out,
                &pad,
                indent,
                state_prefix,
                tap_id,
                tap_actions,
            );
        }
        FlowDir::Wrap => {
            // Treat as row for now
            emit_row_layout(
                children,
                gap,
                center,
                &child_vars,
                out,
                &pad,
                indent,
                state_prefix,
                tap_id,
                tap_actions,
            );
        }
        FlowDir::Layer => {
            // All children at same position (layered)
            for (i, child) in children.iter().enumerate() {
                out.push_str(&format!("{}let {}_rect = __pb;\n", pad, child_vars[i]));
                emit_child_draw(
                    child,
                    &child_vars[i],
                    state_prefix,
                    tap_id,
                    tap_actions,
                    out,
                    indent,
                );
            }
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn emit_column_layout(
    children: &[UiNode],
    gap: f64,
    center: Option<CenterDir>,
    child_vars: &[String],
    out: &mut String,
    pad: &str,
    indent: usize,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
) {
    let n = children.len();
    let g = gap;

    // total height = sum of child heights + gaps
    let height_sum: String = child_vars
        .iter()
        .map(|v| format!("{}_h", v))
        .collect::<Vec<_>>()
        .join(" + ");
    let gaps = if n > 1 {
        format!(" + {:.1} * {:.1}", g, (n - 1) as f64)
    } else {
        String::new()
    };

    out.push_str(&format!("{}let __total_h = {}{};\n", pad, height_sum, gaps));

    // Max width of children
    let width_max: String = child_vars
        .iter()
        .map(|v| format!("{}_w", v))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "{}let __total_w = [{}].iter().cloned().fold(0.0f64, f64::max);\n",
        pad, width_max
    ));

    // Start position based on center
    let start_y = match center {
        Some(CenterDir::Both) | Some(CenterDir::Down) => {
            "__pb.y + (__pb.h - __total_h) / 2.0".to_string()
        }
        _ => "__pb.y".to_string(),
    };
    let start_x = match center {
        Some(CenterDir::Both) | Some(CenterDir::Across) => {
            "__pb.x + (__pb.w - __total_w) / 2.0".to_string()
        }
        _ => "__pb.x".to_string(),
    };

    out.push_str(&format!(
        "{}let __col_x = {};\n{}let mut __col_y = {};\n",
        pad, start_x, pad, start_y
    ));

    for (i, child) in children.iter().enumerate() {
        let cv = &child_vars[i];
        // Each child is centered horizontally within the column
        out.push_str(&format!(
            "{}let {}_rect = Rect {{ x: __col_x + (__total_w - {}_w) / 2.0, y: __col_y, w: {}_w, h: {}_h }};\n",
            pad, cv, cv, cv, cv
        ));
        emit_child_draw(child, cv, state_prefix, tap_id, tap_actions, out, indent);
        if i < children.len() - 1 {
            out.push_str(&format!("{}__col_y += {}_h + {:.1};\n", pad, cv, gap));
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn emit_row_layout(
    children: &[UiNode],
    gap: f64,
    center: Option<CenterDir>,
    child_vars: &[String],
    out: &mut String,
    pad: &str,
    indent: usize,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
) {
    let n = children.len();

    let width_sum: String = child_vars
        .iter()
        .map(|v| format!("{}_w", v))
        .collect::<Vec<_>>()
        .join(" + ");
    let gaps = if n > 1 {
        format!(" + {:.1} * {:.1}", gap, (n - 1) as f64)
    } else {
        String::new()
    };
    out.push_str(&format!("{}let __total_w = {}{};\n", pad, width_sum, gaps));

    let height_max: String = child_vars
        .iter()
        .map(|v| format!("{}_h", v))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "{}let __total_h = [{}].iter().cloned().fold(0.0f64, f64::max);\n",
        pad, height_max
    ));

    let start_x = match center {
        Some(CenterDir::Both) | Some(CenterDir::Across) => {
            "__pb.x + (__pb.w - __total_w) / 2.0".to_string()
        }
        _ => "__pb.x".to_string(),
    };
    let start_y = match center {
        Some(CenterDir::Both) | Some(CenterDir::Down) => {
            "__pb.y + (__pb.h - __total_h) / 2.0".to_string()
        }
        _ => "__pb.y".to_string(),
    };

    out.push_str(&format!(
        "{}let __row_y = {};\n{}let mut __row_x = {};\n",
        pad, start_y, pad, start_x
    ));

    for (i, child) in children.iter().enumerate() {
        let cv = &child_vars[i];
        out.push_str(&format!(
            "{}let {}_rect = Rect {{ x: __row_x, y: __row_y + (__total_h - {}_h) / 2.0, w: {}_w, h: {}_h }};\n",
            pad, cv, cv, cv, cv
        ));
        emit_child_draw(child, cv, state_prefix, tap_id, tap_actions, out, indent);
        if i < children.len() - 1 {
            out.push_str(&format!("{}__row_x += {}_w + {:.1};\n", pad, cv, gap));
        }
    }
}

// Emit measure code for a node — sets {var}_w and {var}_h
fn emit_measure(
    node: &UiNode,
    state_prefix: &str,
    var: &str,
    out: &mut String,
    pad: &str,
) -> (&'static str, &'static str) {
    match node {
        UiNode::Words(w) => {
            let size = text_size(&w.props, 16.0);
            let weight = text_weight_str(&w.props.weight);
            out.push_str(&format!(
                "{0}v_font(\"{1} {2:.0}px system-ui, sans-serif\");\n\
                 {0}let {3}_text = {4};\n\
                 {0}let {3}_w = v_measure(&{3}_text);\n\
                 {0}let {3}_h = {5:.1};\n",
                pad,
                weight,
                size,
                var,
                expr_to_runtime(&w.content, state_prefix),
                size * 1.4
            ));
        }
        UiNode::Tap(t) => {
            let size = text_size(
                &t.props
                    .fill
                    .as_ref()
                    .map(|_| {
                        // Use default font size for tap labels
                        TextProps::default()
                    })
                    .unwrap_or_default(),
                17.0,
            );
            let ph = pad_h(&t.props.padding, 24.0);
            let pv = pad_v(&t.props.padding, 14.0);
            let label = expr_to_runtime(&t.label, state_prefix);
            out.push_str(&format!(
                "{0}v_font(\"600 {1:.0}px system-ui, sans-serif\");\n\
                 {0}let {2}_text = {3};\n\
                 {0}let {2}_w = (v_measure(&{2}_text) + {4:.1} * 2.0).max(80.0);\n\
                 {0}let {2}_h = {5:.1} + {6:.1} * 2.0;\n",
                pad,
                size,
                var,
                label,
                ph,
                size * 1.4,
                pv
            ));
        }
        UiNode::Field(_f) => {
            out.push_str(&format!(
                "{0}let {1}_w = __pb.w;\n{0}let {1}_h = 48.0;\n",
                pad, var
            ));
        }
        UiNode::Image(_) => {
            out.push_str(&format!(
                "{0}let {1}_w = __pb.w.min(300.0);\n{0}let {1}_h = {1}_w * 0.5625;\n",
                pad, var
            ));
        }
        UiNode::Box(b) => {
            out.push_str(&format!("{0}let {1}_w = __pb.w;\n", pad, var));
            if b.props.tall.is_some() {
                out.push_str(&format!("{0}let {1}_h = __pb.h;\n", pad, var));
            } else if b.children.is_empty() {
                let h = prop_f64(&b.props.gap, 0.0); // empty box = gap height or 0
                out.push_str(&format!("{0}let {1}_h = {2:.1};\n", pad, var, h.max(0.0)));
            } else {
                // Recursively measure children to compute actual content height
                let flow = b.props.flow.unwrap_or(FlowDir::Down);
                let gap = prop_f64(&b.props.gap, 0.0);
                let n = b.children.len();
                let child_vars: Vec<String> = (0..n).map(|i| format!("{}_m{}", var, i)).collect();
                for (i, child) in b.children.iter().enumerate() {
                    emit_measure(child, state_prefix, &child_vars[i], out, pad);
                }
                let pv = b
                    .props
                    .padding
                    .as_ref()
                    .map(|p| p.top as f64 + p.bottom as f64)
                    .unwrap_or(0.0);
                match flow {
                    FlowDir::Down => {
                        let h_sum: String = child_vars
                            .iter()
                            .map(|v| format!("{}_h", v))
                            .collect::<Vec<_>>()
                            .join(" + ");
                        let gap_str = if n > 1 {
                            format!(" + {:.1} * {:.1}", gap, (n - 1) as f64)
                        } else {
                            String::new()
                        };
                        out.push_str(&format!(
                            "{0}let {1}_h = {2}{3} + {4:.1};\n",
                            pad, var, h_sum, gap_str, pv
                        ));
                    }
                    _ => {
                        // Across/Wrap/Layer: height = tallest child
                        let h_vals: String = child_vars
                            .iter()
                            .map(|v| format!("{}_h", v))
                            .collect::<Vec<_>>()
                            .join(", ");
                        out.push_str(&format!(
                            "{0}let {1}_h = [{2}].iter().cloned().fold(0.0f64, f64::max) + {3:.1};\n",
                            pad, var, h_vals, pv
                        ));
                    }
                }
            }
        }
        UiNode::Piece(_p) => {
            out.push_str(&format!(
                "{0}let {1}_w = __pb.w;\n{0}let {1}_h = 60.0;\n",
                pad, var
            ));
        }
        UiNode::Each(_) | UiNode::ShowWhen(_) => {
            out.push_str(&format!(
                "{0}let {1}_w = __pb.w;\n{0}let {1}_h = 0.0;\n",
                pad, var
            ));
        }
    }
    ("_w", "_h")
}

// Emit draw code for a child at its computed rect position.
// Sets __pb = {var}_rect then emits the node's draw code within that scope.
fn emit_child_draw(
    node: &UiNode,
    var: &str,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    out: &mut String,
    indent: usize,
) {
    let pad = "    ".repeat(indent);
    out.push_str(&format!("{}{{ let __pb = {}_rect;\n", pad, var));
    let block = emit_node_block(node, state_prefix, tap_id, tap_actions, indent + 1);
    out.push_str(&block.code);
    out.push_str(&format!("{}}}\n", pad));
}

// ─── Individual node emitters ─────────────────────────────────────────────────

fn emit_words(node: &WordsNode, state_prefix: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let size = text_size(&node.props, 16.0);
    let weight = text_weight_str(&node.props.weight);
    let color = node
        .props
        .color
        .as_ref()
        .map(color_to_css)
        .unwrap_or_else(|| "white".to_string());
    let text_expr = expr_to_runtime(&node.content, state_prefix);
    let _align = match node.props.align {
        Some(TextAlign::Center) => "center",
        Some(TextAlign::Right) => "right",
        _ => "left",
    };

    format!(
        "{pad}// words\n\
         {pad}v_font(\"{weight} {size:.0}px system-ui, -apple-system, sans-serif\");\n\
         {pad}v_fill({color:?});\n\
         {pad}let __wt = {text_expr};\n\
         {pad}let __ww = v_measure(&__wt);\n\
         {pad}let __wx = __pb.x + (__pb.w - __ww) / 2.0;\n\
         {pad}v_text(&__wt, __wx, __pb.y + {size:.1} * 1.2);\n",
        pad = pad,
        weight = weight,
        size = size,
        color = color,
        text_expr = text_expr,
    )
}

fn emit_tap(
    node: &TapNode,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    let id = *tap_id;
    *tap_id += 1;

    let label_expr = expr_to_runtime(&node.label, state_prefix);

    let bg = node
        .props
        .fill
        .as_ref()
        .map(fill_expr_to_css)
        .unwrap_or_else(|| "#7f6fe8".to_string());
    let radius = prop_f64(&node.props.radius, 8.0);
    let ph = pad_h(&node.props.padding, 20.0);
    let pv = pad_v(&node.props.padding, 12.0);

    // Hover scale from AnimSpec.to.scale (e.g. hover: scale: 1.05)
    let hover_max_scale: f64 = node
        .props
        .hover
        .as_ref()
        .and_then(|h| h.to.as_ref())
        .and_then(|t| t.scale)
        .unwrap_or(1.0);
    let has_hover_scale = hover_max_scale != 1.0;

    // Register tap action
    tap_actions.push(TapAction {
        id,
        screen_prefix: state_prefix.to_string(),
        body: node.action.clone(),
    });

    let transform_pre = if has_hover_scale {
        format!(
            "{pad}ensure_hover({id}, {ms:.4});\n\
             {pad}let __hs = hover_scale({id});\n\
             {pad}unsafe {{ ved_push_transform(__tx + __tbw / 2.0, __ty + __tbh / 2.0, __hs, __hs); }}\n",
            pad = pad,
            id = id,
            ms = hover_max_scale,
        )
    } else {
        String::new()
    };

    let transform_post = if has_hover_scale {
        format!("{pad}unsafe {{ ved_pop_transform(); }}\n", pad = pad)
    } else {
        String::new()
    };

    format!(
        "{pad}// tap\n\
         {pad}v_font(\"600 17px system-ui, -apple-system, sans-serif\");\n\
         {pad}let __tl = {label_expr};\n\
         {pad}let __tw = v_measure(&__tl);\n\
         {pad}let __tbw = (__tw + {ph:.1} * 2.0).max(80.0);\n\
         {pad}let __tbh = 17.0 * 1.4 + {pv:.1} * 2.0;\n\
         {pad}let __tx = __pb.x + (__pb.w - __tbw) / 2.0;\n\
         {pad}let __ty = __pb.y;\n\
         {transform_pre}\
         {pad}v_fill({bg:?});\n\
         {pad}v_rrect(__tx, __ty, __tbw, __tbh, {radius:.1});\n\
         {pad}v_fill(\"white\");\n\
         {pad}v_text(&__tl, __tx + (__tbw - __tw) / 2.0, __ty + 17.0 * 1.2 + {pv:.1});\n\
         {transform_post}\
         {pad}push_tap(Rect {{ x: __tx, y: __ty, w: __tbw, h: __tbh }}, {id});\n",
        pad = pad,
        label_expr = label_expr,
        ph = ph,
        pv = pv,
        bg = bg,
        radius = radius,
        id = id,
        transform_pre = transform_pre,
        transform_post = transform_post,
    )
}

fn emit_field(
    node: &FieldNode,
    state_prefix: &str,
    _tap_id: &mut u32,
    _tap_actions: &mut Vec<TapAction>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    let placeholder = expr_to_runtime(&node.placeholder, state_prefix);
    let color_str = node
        .props
        .color
        .as_ref()
        .map(color_to_css)
        .unwrap_or_else(|| "#1e1e2e".to_string());
    let radius = prop_f64(&node.props.radius, 8.0);

    format!(
        "{pad}// field\n\
         {pad}v_fill({color:?}); v_rrect(__pb.x, __pb.y, __pb.w, 48.0, {radius:.1});\n\
         {pad}v_fill(\"#666\");\n\
         {pad}v_font(\"400 15px system-ui, sans-serif\");\n\
         {pad}v_text(&{placeholder}, __pb.x + 12.0, __pb.y + 31.0);\n",
        pad = pad,
        color = color_str,
        radius = radius,
        placeholder = placeholder,
    )
}

fn emit_image(node: &ImageNode, state_prefix: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let src = expr_to_runtime(&node.src, state_prefix);
    format!(
        "{pad}// image\n\
         {pad}v_image(&{src}, __pb.x, __pb.y, __pb.w, __pb.h);\n",
        pad = pad,
        src = src,
    )
}

fn emit_piece_call(node: &PieceCall, _state_prefix: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    format!(
        "{pad}render_piece_{}(); // piece\n",
        node.name.to_lowercase(),
        pad = pad,
    )
}

fn emit_each_node(
    node: &EachNode,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    let pad1 = "    ".repeat(indent + 1);

    // The iterator expression — maps to a state field or local var
    let iter_expr = emit_tap_expr(&node.iter, state_prefix);
    let loop_var = format!("__each_{}", node.var);

    // Measure one template child to get per-item height (use first child)
    let item_h = if node.children.is_empty() {
        "0.0".to_string()
    } else {
        // Estimate from first child type
        match &node.children[0] {
            UiNode::Tap(_) => "55.0".to_string(),
            UiNode::Words(w) => format!("{:.1}", text_size(&w.props, 16.0) * 1.4),
            _ => "60.0".to_string(),
        }
    };

    // Emit the draw code for template children, substituting the loop variable
    let mut child_code = String::new();
    for child in &node.children {
        let block = emit_node_block(child, state_prefix, tap_id, tap_actions, indent + 2);
        child_code.push_str(&block.code);
    }

    format!(
        "{pad}// each {var}\n\
         {pad}let __each_{var}_items = {iter};\n\
         {pad}let __each_{var}_h = {item_h};\n\
         {pad}let mut __each_{var}_y = __pb.y;\n\
         {pad}for {loop_var} in __each_{var}_items.iter() {{\n\
         {pad1}let _ = {loop_var};\n\
         {pad1}let __pb = Rect {{ x: __pb.x, y: __each_{var}_y, w: __pb.w, h: __each_{var}_h }};\n\
         {child_code}\
         {pad1}__each_{var}_y += __each_{var}_h;\n\
         {pad}}}\n",
        pad = pad,
        pad1 = pad1,
        var = node.var,
        iter = iter_expr,
        item_h = item_h,
        loop_var = loop_var,
        child_code = child_code,
    )
}

fn emit_show_when(
    node: &ShowWhenNode,
    state_prefix: &str,
    tap_id: &mut u32,
    tap_actions: &mut Vec<TapAction>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    let cond_raw = emit_tap_expr(&node.cond, state_prefix);
    // Strip outer parens added by emit_tap_expr for BinOp — avoids Rust
    // unused_parens warning in generated code.
    let cond = if cond_raw.starts_with('(') && cond_raw.ends_with(')') {
        cond_raw[1..cond_raw.len() - 1].to_string()
    } else {
        cond_raw
    };
    // Always render show_when children against the full viewport so that
    // page-level show_when blocks (used for multi-page navigation) fill the
    // entire canvas rather than a 0-height measurement rect.
    let inner = emit_nodes(
        &node.children,
        "Rect { x: 0.0, y: 0.0, w: vw(), h: vh() }",
        state_prefix,
        tap_id,
        tap_actions,
        indent + 1,
    );
    format!("{}if {} {{\n{}{}}}\n", pad, cond, inner, pad)
}

// ─── Tap dispatch generation ─────────────────────────────────────────────────

fn emit_tap_dispatch(actions: &[TapAction]) -> String {
    let mut out = String::new();
    for action in actions {
        out.push_str(&format!("        {} => {{\n", action.id));
        for stmt in &action.body {
            let rust_stmt = emit_tap_stmt(stmt, &action.screen_prefix);
            out.push_str(&format!("            {}\n", rust_stmt));
        }
        out.push_str("        }\n");
    }
    out
}

fn emit_tap_stmt(stmt: &Stmt, prefix: &str) -> String {
    match stmt {
        Stmt::Assign { target, value, .. } => {
            let lhs = match target {
                AssignTarget::Simple(name, _) => {
                    format!("st().{}_{}", prefix, name)
                }
                AssignTarget::Field(obj, field, _) => {
                    format!("st().{}_{}.{}", prefix, emit_expr(obj), field)
                }
                AssignTarget::Index(obj, _idx, _) => {
                    format!("st().{}_{}", prefix, emit_expr(obj))
                }
            };
            let rhs = emit_tap_expr(value, prefix);
            format!("{} = {};", lhs, rhs)
        }
        Stmt::Let { name, value, .. } => {
            format!("let {} = {};", name, emit_tap_expr(value, prefix))
        }
        Stmt::Give { value, .. } => format!("return {};", emit_tap_expr(value, prefix)),
        Stmt::Expr(e) => format!("{};", emit_tap_expr(e, prefix)),
        Stmt::When {
            arms, otherwise, ..
        } => {
            let mut s = String::new();
            for (i, arm) in arms.iter().enumerate() {
                let kw = if i == 0 { "if" } else { "} else if" };
                s.push_str(&format!("{} {} {{ ", kw, emit_tap_expr(&arm.cond, prefix)));
                for b in &arm.body {
                    s.push_str(&emit_tap_stmt(b, prefix));
                    s.push(' ');
                }
                s.push_str("} ");
            }
            if let Some(other) = otherwise {
                s.push_str(&format!("else {{ {} }}", emit_tap_stmt(other, prefix)));
            }
            s
        }
        _ => String::new(),
    }
}

fn emit_tap_expr(expr: &Expr, prefix: &str) -> String {
    match expr {
        Expr::Ident(name, _) => format!("st().{}_{}", prefix, name),
        Expr::Num(n, _) => n.to_string(),
        Expr::Dec(d, _) => format!("{}_f64", d),
        Expr::Bool(b, _) => b.to_string(),
        Expr::Text(parts, _) => {
            let s: String = parts
                .iter()
                .map(|p| match p {
                    TextPart::Literal(s) => s.clone(),
                    TextPart::Interp(e) => format!("{{{}}}", emit_tap_expr(e, prefix)),
                })
                .collect();
            format!("{:?}", s)
        }
        Expr::BinOp {
            left, op, right, ..
        } => {
            let l = emit_tap_expr(left, prefix);
            let r = emit_tap_expr(right, prefix);
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::NotEq => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::LtEq => "<=",
                BinOp::GtEq => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
                _ => "+",
            };
            format!("({} {} {})", l, op_s, r)
        }
        Expr::Not { expr, .. } => format!("(!{})", emit_tap_expr(expr, prefix)),
        Expr::Neg { expr, .. } => format!("(-{})", emit_tap_expr(expr, prefix)),
        _ => emit_expr(expr),
    }
}

// ─── Render dispatch ─────────────────────────────────────────────────────────

fn emit_render_dispatch(screens: &[&ScreenDef]) -> String {
    if screens.is_empty() {
        return "// no screens".to_string();
    }

    // Clear with background fill of first screen's root box
    let bg = screens
        .first()
        .and_then(|s| s.children.first())
        .and_then(|n| {
            if let UiNode::Box(b) = n {
                b.props.fill.as_ref().map(|f| {
                    let css = fill_expr_to_css(f);
                    hex_to_rgb(&css).unwrap_or((10, 10, 10))
                })
            } else {
                None
            }
        })
        .unwrap_or((10, 10, 10));

    let mut out = format!(
        "unsafe {{ ved_clear({}, {}, {}); }}\n    ",
        bg.0, bg.1, bg.2
    );

    if screens.len() == 1 {
        out.push_str(&format!("render_{}();", screens[0].name.to_lowercase()));
    } else {
        out.push_str("match st().screen {\n");
        for (i, screen) in screens.iter().enumerate() {
            out.push_str(&format!(
                "        {} => render_{}(),\n",
                i,
                screen.name.to_lowercase()
            ));
        }
        out.push_str("        _ => {}\n    }");
    }
    out
}

// ─── Shape structs ───────────────────────────────────────────────────────────

fn emit_shape_struct(shape: &ShapeDef) -> String {
    let fields: Vec<String> = shape
        .fields
        .iter()
        .map(|f| {
            let ty = match &f.ty {
                TypeExpr::Num => "i64",
                TypeExpr::Dec => "f64",
                TypeExpr::Bool => "bool",
                TypeExpr::Text => "&'static str",
                _ => "i64",
            };
            format!("    pub {}: {}", f.name, ty)
        })
        .collect();
    format!(
        "#[derive(Clone, Copy, Debug)]\nstruct {} {{\n{}\n}}\n",
        shape.name,
        fields.join(",\n")
    )
}

// ─── Think functions ─────────────────────────────────────────────────────────

fn emit_think_fn(think: &ThinkDef, tap_id: &mut u32, tap_actions: &mut Vec<TapAction>) -> String {
    let params: Vec<String> = think
        .params
        .iter()
        .map(|p| {
            let ty = match &p.ty {
                TypeExpr::Num => "i64",
                TypeExpr::Dec => "f64",
                TypeExpr::Bool => "bool",
                _ => "i64",
            };
            format!("{}: {}", p.name, ty)
        })
        .collect();

    let mut out = String::new();

    // If there are UI children, emit a render_piece_{name} function
    if !think.ui_children.is_empty() {
        let param_str = params.join(", ");
        let param_names: Vec<&str> = params
            .iter()
            .map(|p| p.split(':').next().unwrap_or("_").trim())
            .collect();
        let node_code = emit_nodes(
            &think.ui_children,
            "Rect { x: 0.0, y: 0.0, w: vw(), h: vh() }",
            "",
            tap_id,
            tap_actions,
            1,
        );
        out.push_str(&format!(
            "fn render_piece_{}({}) {{\n    let _ = ({});\n{}}}\n",
            think.name.to_lowercase(),
            param_str,
            param_names.join(", "),
            node_code,
        ));
    }

    // If there are logic stmts (or no UI children at all), emit a regular fn
    let has_real_stmts = think
        .body
        .iter()
        .any(|s| !matches!(s, Stmt::Expr(Expr::Nothing(_))));
    if has_real_stmts || think.ui_children.is_empty() {
        let ret = match &think.ret {
            Some(TypeExpr::Num) => "i64",
            Some(TypeExpr::Dec) => "f64",
            Some(TypeExpr::Bool) => "bool",
            None => "()",
            _ => "i64",
        };
        let body: Vec<String> = think
            .body
            .iter()
            .filter(|s| !matches!(s, Stmt::Expr(Expr::Nothing(_))))
            .map(|s| format!("    {}", wasm_emit_stmt(s, 1)))
            .collect();
        out.push_str(&format!(
            "fn {}({}) -> {} {{\n{}\n}}\n",
            think.name,
            params.join(", "),
            ret,
            body.join("\n")
        ));
    }

    out
}

// ─── WASM-safe statement emitter ────────────────────────────────────────────
// The shared emit_stmt maps println/print → println!() which doesn't exist in
// no_std. Suppress those and any other std-only calls in the WASM target.
fn wasm_emit_stmt(stmt: &Stmt, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    // Bare identifier: `println;` `print;` etc.
    if let Stmt::Expr(Expr::Ident(name, _)) = stmt {
        if matches!(name.as_str(), "println" | "print" | "input" | "exit") {
            return format!("{}// {} suppressed (no stdout in wasm32)", pad, name);
        }
    }
    // Call: println(...) / print(...)
    if let Stmt::Expr(Expr::Call { func, .. }) = stmt {
        if let Expr::Ident(name, _) = func.as_ref() {
            if matches!(name.as_str(), "println" | "print" | "input" | "exit") {
                return format!("{}// {} suppressed (no stdout in wasm32)", pad, name);
            }
        }
    }
    // Bare string literal — leaked argument from a suppressed println/print call.
    if let Stmt::Expr(Expr::Text(_, _)) = stmt {
        return format!("{}// string suppressed (no stdout in wasm32)", pad);
    }
    emit_stmt(stmt, indent)
}

// ─── Helper utilities ────────────────────────────────────────────────────────

fn find_main_screen(program: &Program) -> Option<&ScreenDef> {
    program.items.iter().find_map(|i| {
        if let Item::Screen(s) = i {
            Some(s)
        } else {
            None
        }
    })
}

fn fill_expr_to_css(expr: &Expr) -> String {
    match expr {
        Expr::Color(c, _) => {
            if c.starts_with('#') {
                c.clone()
            } else {
                format!("#{}", c)
            }
        }
        Expr::Ident(s, _) => s.clone(),
        Expr::Text(parts, _) => {
            let s: String = parts
                .iter()
                .map(|p| match p {
                    TextPart::Literal(l) => l.clone(),
                    _ => String::new(),
                })
                .collect();
            if s.starts_with('#') {
                s
            } else {
                format!("#{}", s)
            }
        }
        _ => "#000000".to_string(),
    }
}

fn color_to_css(color: &ColorExpr) -> String {
    match color {
        ColorExpr::Hex(h) => {
            if h.starts_with('#') {
                h.clone()
            } else {
                format!("#{}", h)
            }
        }
        ColorExpr::Named(n) => n.clone(),
        ColorExpr::Fade(a, _b) => a.clone(),
    }
}

fn hex_to_rgb(hex: &str) -> Option<(u8, u8, u8)> {
    let h = hex.trim_start_matches('#');
    if h.len() == 6 {
        let r = u8::from_str_radix(&h[0..2], 16).ok()?;
        let g = u8::from_str_radix(&h[2..4], 16).ok()?;
        let b = u8::from_str_radix(&h[4..6], 16).ok()?;
        Some((r, g, b))
    } else if h.len() == 3 {
        let r = u8::from_str_radix(&h[0..1].repeat(2), 16).ok()?;
        let g = u8::from_str_radix(&h[1..2].repeat(2), 16).ok()?;
        let b = u8::from_str_radix(&h[2..3].repeat(2), 16).ok()?;
        Some((r, g, b))
    } else {
        None
    }
}

fn text_size(props: &TextProps, default: f64) -> f64 {
    match &props.size {
        Some(Expr::Num(n, _)) => *n as f64,
        Some(Expr::Dec(d, _)) => *d,
        _ => default,
    }
}

fn text_weight_str(weight: &Option<TextWeight>) -> &'static str {
    match weight {
        Some(TextWeight::Fat) => "700",
        Some(TextWeight::Thin) => "300",
        _ => "400",
    }
}

fn prop_f64(expr: &Option<Expr>, default: f64) -> f64 {
    match expr {
        Some(Expr::Num(n, _)) => *n as f64,
        Some(Expr::Dec(d, _)) => *d,
        _ => default,
    }
}

fn pad_h(padding: &Option<PaddingExpr>, default: f64) -> f64 {
    padding.as_ref().map(|p| p.right as f64).unwrap_or(default)
}

fn pad_v(padding: &Option<PaddingExpr>, default: f64) -> f64 {
    padding.as_ref().map(|p| p.top as f64).unwrap_or(default)
}

/// Convert a VED expression to a raw Rust display value (for use inside format! args).
/// Returns an expression that implements Display — NOT wrapped in Cow.
fn expr_to_display(expr: &Expr, state_prefix: &str) -> String {
    match expr {
        Expr::Num(n, _) => n.to_string(),
        Expr::Dec(d, _) => format!("{d}f64"),
        Expr::Bool(b, _) => b.to_string(),
        Expr::Ident(name, _) => {
            if !state_prefix.is_empty() {
                format!("st().{}_{}", state_prefix, name)
            } else {
                "\"\"".to_string()
            }
        }
        Expr::Text(parts, _) => {
            let all_literal = parts.iter().all(|p| matches!(p, TextPart::Literal(_)));
            if all_literal {
                let s: String = parts
                    .iter()
                    .map(|p| match p {
                        TextPart::Literal(s) => s.clone(),
                        _ => String::new(),
                    })
                    .collect();
                format!("{:?}", s)
            } else {
                let mut fmt = String::new();
                let mut args: Vec<String> = Vec::new();
                for part in parts {
                    match part {
                        TextPart::Literal(s) => {
                            fmt.push_str(&s.replace('{', "{{").replace('}', "}}"))
                        }
                        TextPart::Interp(e) => {
                            fmt.push_str("{}");
                            args.push(expr_to_display(e, state_prefix));
                        }
                    }
                }
                format!("format!({:?}, {})", fmt, args.join(", "))
            }
        }
        _ => "\"\"".to_string(),
    }
}

/// Convert a VED expression to a `Cow<str>` Rust expression for canvas text APIs.
fn expr_to_runtime(expr: &Expr, state_prefix: &str) -> String {
    match expr {
        Expr::Text(parts, _) => {
            let all_literal = parts.iter().all(|p| matches!(p, TextPart::Literal(_)));
            if all_literal {
                let s: String = parts
                    .iter()
                    .map(|p| match p {
                        TextPart::Literal(s) => s.clone(),
                        _ => String::new(),
                    })
                    .collect();
                format!("alloc::borrow::Cow::Borrowed({:?})", s)
            } else {
                let mut fmt = String::new();
                let mut args: Vec<String> = Vec::new();
                for part in parts {
                    match part {
                        TextPart::Literal(s) => {
                            fmt.push_str(&s.replace('{', "{{").replace('}', "}}"))
                        }
                        TextPart::Interp(e) => {
                            fmt.push_str("{}");
                            // Use display variant so we don't double-wrap in Cow
                            args.push(expr_to_display(e, state_prefix));
                        }
                    }
                }
                format!(
                    "alloc::borrow::Cow::Owned(format!({:?}, {}))",
                    fmt,
                    args.join(", ")
                )
            }
        }
        Expr::Num(n, _) => format!("alloc::borrow::Cow::Borrowed(\"{n}\")"),
        Expr::Dec(d, _) => format!("alloc::borrow::Cow::Owned(format!(\"{{:.2}}\", {d}f64))"),
        Expr::Bool(b, _) => format!("alloc::borrow::Cow::Borrowed(\"{b}\")"),
        Expr::Ident(name, _) => {
            if !state_prefix.is_empty() {
                format!(
                    "alloc::borrow::Cow::Owned(format!(\"{{}}\", st().{}_{}))",
                    state_prefix, name
                )
            } else {
                "alloc::borrow::Cow::Borrowed(\"\")".to_string()
            }
        }
        _ => "alloc::borrow::Cow::Borrowed(\"\")".to_string(),
    }
}

fn unique_id(node: &BoxNode) -> u64 {
    // Use pointer address as unique id for variable naming
    node as *const _ as u64
}

fn write_file(path: impl AsRef<Path>, content: &str) -> CompileResult<()> {
    std::fs::write(&path, content).map_err(|e| crate::compiler::CompileError {
        message: format!("Failed to write {}: {}", path.as_ref().display(), e),
        span: (0..0).into(),
    })
}

// ─── Ghost intents (unchanged) ───────────────────────────────────────────────

fn generate_ghost_intents(program: &Program) -> String {
    let mut out = String::from("{\n  \"screens\": [\n");
    let mut first = true;
    for item in &program.items {
        let Item::Screen(screen) = item else { continue };
        if !screen.ghost {
            continue;
        }
        if !first {
            out.push_str(",\n");
        }
        first = false;
        out.push_str(&format!(
            "    {{ \"name\": \"{}\", \"intents\": [{}] }}",
            json_escape(&screen.name),
            screen
                .intents
                .iter()
                .map(|i| format!("\"{}\"", json_escape(i)))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    if first {
        return String::new();
    }
    out.push_str("\n  ]\n}\n");
    out
}

fn json_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}
